version: '3.8'

services:
  hr-portal:
    build:
      context: ./services/hr
      dockerfile: Dockerfile
    environment:
      - MSSQL_HOST=${MSSQL_HOST}
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DB=${MSSQL_DB}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME_HR}
      - DB_CONNECTION_RETRIES=10
      - DB_RETRY_BASE_DELAY=5000
      - DB_RETRY_MAX_DELAY=30000
      - HR_PORTAL_PORT=${HR_PORTAL_PORT}
    volumes:
      - ./services/shared:/app/shared:ro
    ports:
      - "${HR_PORTAL_PORT}:3000"
    deploy:
      resources:
        limits:
          memory: 15G
        reservations:
          memory: 15G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - app-network

  k6:
    image: grafana/k6
    volumes:
      - ./k6/scripts:/scripts
    environment:
      - HR_PORTAL_URL=${HR_PORTAL_URL}
    depends_on:
      hr-portal:
        condition: service_healthy
    command: run /scripts/load-test.js
    networks:
      - app-network

volumes:
  sqldata:

networks:
  app-network: