version: '3.8'

services:    
  test-app:
    build:
      context: ./services
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=Test-App
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
      - NEW_RELIC_LOG=stdout
#      - NODE_ENV=production
    ports:
      - "${TEST_APP_PORT}:3000"
    mem_limit: 2G

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    environment:
      - TEST_APP_URL=http://test-app:4000
    depends_on:
      - test-app
    command: run /scripts/load-test.js
