version: '3.8'

services:
  movie-matrix:
    build:
      context: ./services
    environment:
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_USER=${PSQL_USER}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_DATABASE=${PSQL_DATABASE}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=Movie-Matrix
#      - NEW_RELIC_NO_CONFIG_FILE=true
#      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
#      - NEW_RELIC_LOG=stdout
#      - NODE_ENV=production
    ports:
      - "5001-5002:5000"
    networks:
      - movie-network
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    environment:
      - MOVIE_MATRIX_URL=http://movie-matrix:5000
    depends_on:
      - movie-matrix
    command: run /scripts/load-test.js
    networks:
      - movie-network
networks:
  movie-network:
    driver: bridge