version: '3.8'

services:    
  hr-app:
    build:
      context: ./services
    environment:
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_USER=${PSQL_USER}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_DATABASE=${PSQL_DATABASE}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=HR-App
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
      - NEW_RELIC_LOG=stdout
#      - NODE_ENV=production
    ports:
      - "${HR_APP_PORT}:4000"
    deploy:
      resources:
        limits:
          memory: 25G
        reservations:
          memory: 25G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    environment:
      - HR_APP_URL=http://hr-app:4000
    depends_on:
      - hr-app
    command: run /scripts/load-test.js
